name = "do-taskmanager2"
main = "src/index.ts"
compatibility_date = "2022-06-07"
node_compat=true

[durable_objects]
bindings = [
  { name = "TEST_DO", class_name = "Test_DO" }
]

[[migrations]]
tag = "v1"
new_classes = ["Test_DO"]